### ISSUE TITLE
r8152 not working under 6.12.3 but working well under 6.12.2

### ISSUE THREAD

**Issue by zyystudio** [jinlife/unraid-r8125-r8152-driver#5]
upgrade from 6.12.2 to 6.12.3 but find this plugin [r8152-20230714-6.3.13-Unraid-1.txz](https://github.com/jinlife/unraid-r8125-r8152-driver/releases/download/6.3.13-Unraid/r8152-20230714-6.3.13-Unraid-1.txz) not working
any hint or work around?
Thanks

**Comment by zyystudio** [comment]
btw, the kernel of unraid6.12.2 is 6.1.36 while unraid6.12.3 is 6.1.38.

**Comment by zyystudio** [comment]
Solved! My mistake!
FYI
I download the r8152-20230709-6.1.38-Unraid-1.txz and r8152-20230709-6.1.38-Unraid-1.txz.md5
and create one folder config\plugins\r8152-driver\packages\6.1.38\ and put them there
everything works well then.

Please close it.
Thanks

**Comment by jinlife** [comment]
Thanks for the notice.
