### ISSUE TITLE
WOL not working on Unraid 

### ISSUE THREAD

**Issue by failbit** [jinlife/unraid-r8125-r8152-driver#9]
Hello,

I switched to a 2.5Gbit / RTL8125-Card in my Unraid and use this driver. WOL is not working for me with this combination, another card I used before just worked fine. On Shutdown im setting "ethtool -s eth0 wol g" for that NIC. 

Is there a known limitation with WOL not working with this driver in Unraid? 

Regards

**Comment by jinlife** [comment]
It seems the WOL is enabled in the source code. I have no idea why yours is not working. 
Please use unraid built-in drivers if it is working.
